### ISSUE TITLE
Is column width definable ?

### ISSUE THREAD

**Issue by soniram** [daniel-nagy/md-data-table#106]
How can I define deferring column widths ?

**Comment by daniel-nagy** [comment]
You can do this easily with CSS.

```css
/* all cells in column 2 will have a minimum width of 200px */
tbody > tr > td:nth-child(2) {
  min-width: 200px;
} 
```
 You could also slap a CSS class on the cell and set it's min / max width. Currently there is no way to do this in the module.
