### ISSUE TITLE
fixed column width

### ISSUE THREAD

**Issue by Soulcyber** [daniel-nagy/md-data-table#123]
i have a list of data, with variable string value, i noticed that after a page change where is a long cell value with a cell larger than the page before, the table resizes the columns width which means a very bad visual experience when there are a lot of pages to navigate
CodePen here: http://codepen.io/anon/pen/ojgqxr
change page to see what i mean

Is there a way to fix the column width to a certain amount?
if i have a large string i would prefer the row height to be higher or split the string inside the cell in 2 lines.

Is there some module properties or tip&tricks with CSS to do that?
Thanks :)

**Comment by daniel-nagy** [comment]
You can do this with css.

```css
/* if you want to fix the width of every cell in column 1 */
table.my-class > tbody > tr > td:first-child {
  max-width: 200px;
}
```

Or you can use a CSS class.

```css
/* only cells with the fixed-width class will have a max width */
table.my-class > tbody > tr > td.fixed-width {
  max-width: 200px;
}
```

**Comment by daniel-nagy** [comment]
When I do this in the [Codepen](http://codepen.io/anon/pen/NGPYJY) it bleeds into the neighboring cell; however, when I do it locally it works as expected and wraps the text within the cell. Let me know if this works or not for you.

**Comment by Soulcyber** [comment]
```css
table[md-data-table] > tbody > tr > td:nth-child(1) {
  width: 100px;
  word-wrap: break-word;
}
```
this seems to fix the problem, i will test it more when i'll have time :)

a big thanks for now :+1:
