### ISSUE TITLE
Table background is hardcoded

### ISSUE THREAD

**Issue by nestorbritez** [daniel-nagy/md-data-table#135]
Currently the table's background is hardcoded to white.
```css
table[md-data-table] {
  background-color: #fff;
}
```
According to angular material this should follow the same style of md-content (A100) configured in `backgroundPalette`
