### ISSUE TITLE
Rows are highlighted upon hover even when md-disable-select is added

### ISSUE THREAD

**Issue by hkjels** [daniel-nagy/md-data-table#190]
```css
md-data-table-container table tbody [md-disable-select]:hover {
  background-color: transparent !important;
}
```
Need to add something like that to the stylesheet.
Which also reveals another issue, the specificity-graph of the stylesheet is awful.
This should have been possible with
```css
md-data-table-container [md-disable-select]:hover {
  background-color: transparent;
}
```
