### ISSUE TITLE
Progress bar 'bumps' the md-body down

### ISSUE THREAD

**Issue by pdore-netfore** [daniel-nagy/md-data-table#244]
When using the md-progress option, the table's body 'jitters' when the progress bar is shown/hidden.

i.e. When sorting, the progress bar shows and then hides, pushing the body down, then back up.

**Comment by daniel-nagy** [comment]
What happens if you use the following CSS

```CSS
.md-table-progress md-progress-linear .md-container {
  position: absolute;
}
```
