### ISSUE TITLE
Row Selection Background Color

### ISSUE THREAD

**Issue by daniel-nagy** [daniel-nagy/md-data-table#3]
When a row is selected its background color should be darkened to Grey 100 (#F5F5F5).

the following css class is available,

```css
table[md-data-table] > tbody > tr.md-selected {
  background-color: #f5f5f5;
}
```

The issue is adding and removing the class appropriately when the row is selected.
