### ISSUE TITLE
rowSelection can't be disabled

### ISSUE THREAD

**Issue by trahloff** [daniel-nagy/md-data-table#308]
The dropdown that enables the user to choose how many rows of the table should be displayed can't be disabled with a simple option flag.
![pieceofshitake](https://cloud.githubusercontent.com/assets/16914641/13531851/e8d3623a-e228-11e5-9a26-06de4fc68109.JPG)
The only solution is to delete line 20-26 in `md-data-table.js`.

I think there should be a solution that is more straight forward.

PS: Yes, I've tried:
```javascript 
option = {rowSelection: false}
```

**Comment by daniel-nagy** [comment]
I've received requests to be able to disable the row select options a few times now. In the mean time you can remove it pretty easily with CSS.

**Comment by trahloff** [comment]
Could you please demonstrate how to do this

**Comment by daniel-nagy** [comment]
It looks like you want to show the page select but hide the limit select.

```css
.md-table-pagination {
  .md-table-select:nth-of-type(2) {
    display: none;
  }
}
```

You can hide the labels as well. You can use child selectors to choose which labels to hide.

```css
.md-table-pagination {
  /* this will hide all labels */
  .label {
    display: none;
  }
}
```

**Comment by trahloff** [comment]
I couldn't get it to work with your CSS but I found a workaround that sadly only works with hiding both selects:
```css
  md-select.md-table-select > .md-select-value {
    display: none;
  }
```

**Comment by daniel-nagy** [comment]
You probably just need to un-nest it if you are not using a CSS preprocessor.

```css
.md-table-pagination .md-table-select:nth-of-type(2) {
  display: none;
}
```

I just tried it and it worked.
