### ISSUE TITLE
Is there a way to have fixed-width columns?

### ISSUE THREAD

**Issue by pdore-netfore** [daniel-nagy/md-data-table#311]

**Comment by brunofin** [comment]
```css
table.md-table td.md-cell {
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
    min-width: 100px;
    max-width: 100px;
}
```

**Comment by daniel-nagy** [comment]
You can set the width of the cells as @brunofin did or if you want all the cells to be the same width, but not necessarily a specific width, you can set the `table-layout` property to `fixed`.

```css
table.md-table {
    table-layout: fixed;
}
```

**Comment by pdore-netfore** [comment]
@daniel-nagy This breaks the header layout ...

**Comment by daniel-nagy** [comment]
I believe I need to change line [94](https://github.com/daniel-nagy/fixed-table-header/blob/master/src/fixed-table-header.js#L94) from
```javascript
clone.css('minWidth', style.width);
```
to 
```javascript
clone.css({minWidth: style.width, maxWidth: style.width});
```

But if you are using `table-layout: fixed;` you will probably also want to allow the header cells to wrap text.

```css
table.md-table th {
    white-space: normal !important;
}
```

But I wouldn't recommend using `table-layout: fixed;` in the first place because your table will end up looking something like this

<img width="541" alt="screen shot 2016-03-11 at 12 08 13 pm" src="https://cloud.githubusercontent.com/assets/1622446/13709427/f748adda-e781-11e5-9dbc-8ce9efcc570d.png">

As you can see, instead of scrolling horizontally the columns bleed into one other to fit on the page. Instead I would give each column the same percentage width. This will set the width of the column to `max(naturalWidth, percentWidth)` and the table will scroll horizontally if it needs to.

```Less
// number of columns not counting the first column if row selection is enabled
@column-count: 7;

// :not(.clone) may or may not be necessary
// without checkboxes
table.md-table:not(.clone) {
  th {
    width: (100% / @column-count);
  }
}

// with checkboxes
table.md-table.md-row-select:not(.clone) {
  th:nth-child(n+2) {
    width: (100% / @column-count);
  }
}
```

**Comment by brunofin** [comment]
I'm using a mixin in my SCSS: to set a width to each column including its header. The column with width not set will most likely fill the remaining space.

```scss
@mixin table-cell-width($child, $width, $padding: 0px) {
  td.md-cell:nth-child(#{$child}),
  th.md-column:nth-child(#{$child}) {
    min-width: $width !important;
    max-width: $width !important;
    padding: $padding !important;
  }
}

// then...

  @include table-cell-width(1, 20px);
  @include table-cell-width(2, 16px);
  @include table-cell-width(3, 39px, 0 15px 0 0);
  @include table-cell-width(4, 40px);
  @include table-cell-width(5, 90px, 0 15px 0 0);
  @include table-cell-width(6, 170px, 0 15 0 0);
  @include table-cell-width(7, 65px, 0 15px 0 0);
  @include table-cell-width(8, 30px, 0 15px 0 0);
  @include table-cell-width(9, 40px, 0 15px 0 0);
  @include table-cell-width(10, 70px, 0 15px 0 0);
  @include table-cell-width(11, 40px, 0 15px 0 0);
  @include table-cell-width(12, 70px);
```
