### ISSUE TITLE
Possible to hide all checkboxes but maintain row select ability?

### ISSUE THREAD

**Issue by jbdivups** [daniel-nagy/md-data-table#314]

**Comment by daniel-nagy** [comment]
I suppose you could hide the checkboxes with CSS.

```css
.md-checkbox-column,
.md-checkbox-cell {
  display: none;
}
```
