### ISSUE TITLE
Animation on row(s) that being deleted

### ISSUE THREAD

**Issue by L1ncx** [daniel-nagy/md-data-table#322]
I want to put an animation effect on the rows thats being deleted (ei. slide down or fade out). Is there something like row-deleted callback function where we can manipulate the `row` element or something like that?

**Comment by WDShannon** [comment]
Anybody have a solution for this?  Any animation I try to implement ends up not working on the TR.  I am trying to get something animating for rows entering and leaving.

**Comment by daniel-nagy** [comment]
Overwrite this CSS,

```css
table.md-table tr.md-row[ng\:repeat].ng-leave,
table.md-table tr.md-row[ng-repeat].ng-leave,
table.md-table tr.md-row[x-ng-repeat].ng-leave,
table.md-table tr.md-row[data-ng-repeat].ng-leave {
  display: none;
}
```
