### ISSUE TITLE
Text-Wrap and restrict column header width

### ISSUE THREAD

**Issue by panickerr** [daniel-nagy/md-data-table#462]
Hi Guys,
Is there a way to restrict the width of the individual columns in the header so that i can split lengthy column names into separate lines ?

BR

**Comment by daniel-nagy** [comment]
Try using

```css
th.md-column {
  white-space: normal;
}
```

**Comment by panickerr** [comment]
@daniel-nagy thanks man. But it works only when i embed that in style within the <th> tag and fails to work when i use it was a class outside and call it.

**Comment by daniel-nagy** [comment]
You'll need to use a more specific selector to overwrite the default style

```css
// this is the default
table.md-table th.md-column {
  white-space: nowrap;
}
```

Or use `!important`.
